# Generated by Django 4.0.3 on 2022-04-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default='yjyang', max_length=10),
        ),
    ]
